package ies.quevedo.rpgchardatcompose.framework.theme

import androidx.annotation.ColorInt
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF4658a9)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFdde1ff)
val md_theme_light_onPrimaryContainer = Color(0xFF00115a)
val md_theme_light_secondary = Color(0xFF5a5d71)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFdfe1fa)
val md_theme_light_onSecondaryContainer = Color(0xFF171a2c)
val md_theme_light_tertiary = Color(0xFF76536e)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffd7f5)
val md_theme_light_onTertiaryContainer = Color(0xFF2c1228)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfefbff)
val md_theme_light_onBackground = Color(0xFF1b1b1f)
val md_theme_light_surface = Color(0xFFfefbff)
val md_theme_light_onSurface = Color(0xFF1b1b1f)
val md_theme_light_surfaceVariant = Color(0xFFe2e1ec)
val md_theme_light_onSurfaceVariant = Color(0xFF45464f)
val md_theme_light_outline = Color(0xFF76767f)
val md_theme_light_inverseOnSurface = Color(0xFFf3f0f5)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inversePrimary = Color(0xFFb8c4ff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFb8c4ff)
val md_theme_dark_onPrimary = Color(0xFF132879)
val md_theme_dark_primaryContainer = Color(0xFF2d4090)
val md_theme_dark_onPrimaryContainer = Color(0xFFdde1ff)
val md_theme_dark_secondary = Color(0xFFc3c5dd)
val md_theme_dark_onSecondary = Color(0xFF2c2f41)
val md_theme_dark_secondaryContainer = Color(0xFF43465a)
val md_theme_dark_onSecondaryContainer = Color(0xFFdfe1fa)
val md_theme_dark_tertiary = Color(0xFFe4bad8)
val md_theme_dark_onTertiary = Color(0xFF44263e)
val md_theme_dark_tertiaryContainer = Color(0xFF5c3c55)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd7f5)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1b1b1f)
val md_theme_dark_onBackground = Color(0xFFe4e1e6)
val md_theme_dark_surface = Color(0xFF1b1b1f)
val md_theme_dark_onSurface = Color(0xFFe4e1e6)
val md_theme_dark_surfaceVariant = Color(0xFF45464f)
val md_theme_dark_onSurfaceVariant = Color(0xFFc6c5cf)
val md_theme_dark_outline = Color(0xFF90909a)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1b1f)
val md_theme_dark_inverseSurface = Color(0xFFe4e1e6)
val md_theme_dark_inversePrimary = Color(0xFF4658a9)
val md_theme_dark_shadow = Color(0xFF000000)


val seed = Color(0xFF0f1a48)

@ColorInt
val error = Color(0xFFba1b1b)